# Strings

In [1]:
a = "This is our first class"

In [2]:
type(a)

str

In [3]:
b = 5
type(b)

int

In [5]:
c = 5.4
type(c)

float

In [6]:
# finding the length
len(a)

23

In [7]:
#strings have index
a[0],a[1],a[2],a[3]

('T', 'h', 'i', 's')

In [8]:
#last index
a[-1]

's'

In [10]:
# 2nd last index
a[-3]

'a'

In [13]:
#slicing the string
a[:10]

'This is ou'

In [15]:
a[22]

's'

In [14]:
a[10:23]

'r first class'

In [17]:
a[:]

'This is our first class'

In [22]:
newstr = 'Data Science is the future'
newstr[ : :2]

'Dt cec steftr'

In [19]:
newstr = 'aa bb cc'
newstr[::3]

'abc'

In [20]:
newstr = 'aa bb cc'
newstr[::-1]

'cc bb aa'

In [21]:
newstr = 'a b c'
newstr[::-2]

'cba'

In [23]:
a

'This is our first class'

In [35]:
a.split(' ')

['This', 'is', 'our', 'first', 'class']

In [26]:
a.split('i')

['Th', 's ', 's our f', 'rst class']

In [29]:
text = 'Because we dont want to be using 70,000 digits in some calculations we’ll take a random subset of the digits. The randomisation is important as the dataset is sorted by its label (i.e., the first seven thousand or so are zeros, etc.). To ensure randomisation we’ll create a random permutation of the number 0 to 69,999 which allows us later to select the first five or ten thousand for our calculations and visualisations.'

In [31]:
wordlist = text.split(' ')

In [33]:
len(wordlist)

73

In [27]:
#striping a string
txt = ",,,,,rrttgg.....banana....rrr"
x = txt.strip(",.grt")
print(x)

banana


In [28]:
#common use
newstr1 = ' Mumbai'
newstr2 = 'Mumbai'
newstr3 = 'Mumbai '

newstr1.strip(" "),newstr2.strip(" "),newstr3.strip(" ")

('Mumbai', 'Mumbai', 'Mumbai')

# Lists and tuples

In [36]:
tuple1 = ('char',2,2.3)

In [37]:
tuple1

('char', 2, 2.3)

In [38]:
tuple1[0],tuple1[1]

('char', 2)

In [39]:
List1 = ['char',2,2.3]

In [40]:
List1[3]

IndexError: list index out of range

In [41]:
List1.append('4th element')

In [42]:
List1

['char', 2, 2.3, '4th element']

In [43]:
tuple1.append('4th element')

AttributeError: 'tuple' object has no attribute 'append'

In [44]:
List2 = [0,12,3,4,19]

In [45]:
List2.sort()

In [46]:
List2

[0, 3, 4, 12, 19]

In [47]:
List2.reverse()

In [48]:
List2

[19, 12, 4, 3, 0]

# For Loop

In [53]:
x = range(2,10)

In [54]:
x

range(2, 10)

In [55]:
x[0],x[1],x[2]

(2, 3, 4)

In [56]:
len(x)

8

In [58]:
for i in range(30):
    #print(i)
    print(i+10)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [60]:
a = 'This is our first class'
for i in a[:5]:
     print(i)

T
h
i
s
 


In [61]:
len(a)

23

In [63]:
#alternate    
for i in range(len(a)):
    print('index : ',i,' value : ',a[i])

index :  0  value :  T
index :  1  value :  h
index :  2  value :  i
index :  3  value :  s
index :  4  value :   
index :  5  value :  i
index :  6  value :  s
index :  7  value :   
index :  8  value :  o
index :  9  value :  u
index :  10  value :  r
index :  11  value :   
index :  12  value :  f
index :  13  value :  i
index :  14  value :  r
index :  15  value :  s
index :  16  value :  t
index :  17  value :   
index :  18  value :  c
index :  19  value :  l
index :  20  value :  a
index :  21  value :  s
index :  22  value :  s


In [70]:
a = 'This is our first class'

In [72]:
len(a.split(' '))

5

In [65]:
count = 0
for i in a:
    if i == ' ':
        count = count + 1
print('Total no. of words : ',count+1)

Total no. of words :  5


In [66]:
#Make a list of vowels from the given list
a = 'Timothy Astor King'
vowellist = []
for i in a:
    
    if i in "aieou":
        vowellist.append(i)

In [67]:
vowellist

['i', 'o', 'o', 'i']

In [68]:
#remove duplicates from the given list
a = [10,20,30,40,10,50,50]
l1 = []
for i in a:
    if i not in l1:
        l1.append(i)

In [69]:
l1

[10, 20, 30, 40, 50]

# NUMPY

In [ ]:
numpy - numerical python
pandas = python data analysis

In [74]:
import numpy as np

In [75]:
# Define an array arr with integer elements 1,2,3 and 4
integerArray = np.array([1,2,3,4], int)

In [76]:
# We can access these elements by using index values
print(integerArray[0])

1


In [77]:
# We can also use ranges to access values
print(integerArray[:2])

[1 2]


In [80]:
# Find if a value exists in the array
# Returns true if value exists else returns false
print(3 in integerArray)

True


In [81]:
integerArray2 = np.array([5,6], int)
# Concatenate two arrays
print(np.concatenate((integerArray, integerArray2)))

[1 2 3 4 5 6]


In [82]:
# Array of zeros
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [83]:
# Array of ones with type int
print(np.ones(10, dtype=int))

[1 1 1 1 1 1 1 1 1 1]


In [84]:
# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[0 1 2 3 4 5 6 7 8 9]


In [85]:
# Multidimensional array
floatArray = np.array([[1,2,3], [4,5,6]], float)
print(floatArray)

[[1. 2. 3.]
 [4. 5. 6.]]


In [86]:
floatArray.shape

(2, 3)

In [87]:
rangeArray.shape

(10,)

In [88]:
# Convert one dimensional to multidimensional arrays
rangeArray = rangeArray.reshape(5, 2)
print(rangeArray)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [89]:
# Convert multidimensional to one dimensional array
rangeArray = rangeArray.flatten()
print(rangeArray)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
import numpy as np

In [13]:
# Concatenation of multi-dimensional arrays
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(arr1,'\n')
print(arr2,'\n')
print(np.concatenate((arr1, arr2)))

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Operations

In [14]:
#Operations
print("Array 1 \n {}".format(arr1))

Array 1 
 [[1 2]
 [3 4]]


In [15]:
# Addition
print("Array 1 + Array 2\n {}".format(arr1 + arr2))

Array 1 + Array 2
 [[ 6  8]
 [10 12]]


In [16]:
# Multiplication
print("Array 1 * Array 2\n {}".format(arr1 * arr2))

Array 1 * Array 2
 [[ 5 12]
 [21 32]]


In [17]:
# Square root
print("Square root of Array 1\n {}".format(np.sqrt(arr1)))

Square root of Array 1
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [18]:
# Log
print("Square root of Array 1\n {}".format(np.log(arr1)))

Square root of Array 1
 [[0.         0.69314718]
 [1.09861229 1.38629436]]


In [19]:
# Sum of array elements
print("Sum of elements of Array 1: {}".format(arr1.sum()))

Sum of elements of Array 1: 10


In [20]:
# Mean of array elements
print("Mean of elements of Array 1: {}".format(arr1.mean()))

Mean of elements of Array 1: 2.5


In [21]:
# Min of array elements
print("Min of elements of Array 1: {}".format(arr1.min()))

Min of elements of Array 1: 1


In [22]:
# max of array elements
print("Min of elements of Array 1: {}".format(arr1.max()))

Min of elements of Array 1: 4


In [23]:
# standard deviation of array elements
print("Min of elements of Array 1: {}".format(arr1.std()))

Min of elements of Array 1: 1.118033988749895


In [24]:
sampleArray = np.array([[5,2,3], [3,4,5], [1,1,1]], int)
print("Sample Array\n {}".format(sampleArray))

Sample Array
 [[5 2 3]
 [3 4 5]
 [1 1 1]]


In [25]:
# Get unqiue values
print("Unique values: {}".format(np.unique(sampleArray)))

Unique values: [1 2 3 4 5]


In [26]:
# Get diagonal values
print("Diagonal\n {}".format(sampleArray.diagonal()))

Diagonal
 [5 4 1]


In [27]:
# Sort values in the multidimensional array
print("Sorted\n {}".format(np.sort(sampleArray)))

Sorted
 [[2 3 5]
 [3 4 5]
 [1 1 1]]


# Random arrays

In [28]:
# Random array
print("Random array: {}".format(np.random.rand(5)))

Random array: [0.63790783 0.1866343  0.67222785 0.89658017 0.01740587]


In [29]:
# Random matrix
print("Random matrix:\n {}".format(np.random.rand(5,4)))

Random matrix:
 [[0.81759988 0.96332181 0.57804942 0.94795034]
 [0.98475472 0.88382561 0.80151739 0.0995686 ]
 [0.52234578 0.89647806 0.90199546 0.72869968]
 [0.84843371 0.5966655  0.62108414 0.41097568]
 [0.86948704 0.98181041 0.3909134  0.98843351]]


In [39]:
# Random array of integers in a range (say 0-9)

#floor return the input part of the array
randomArray = np.floor(np.random.rand(10) * 10)

print("Random integer array: {}".format(randomArray))

Random integer array: [4. 2. 0. 3. 5. 1. 4. 7. 3. 5.]


In [40]:
# Futher simplification

print("Random matrix:\n{}".format(np.random.randint(0, 10, (2,5))))

print("Random matrix:\n{}".format(np.random.randint(0, 10, (5))))

Random matrix:
[[9 9 9 7 4]
 [9 1 1 5 0]]
Random matrix:
[1 9 6 3 4]


# Masking and slicing

In [43]:
bigarray=np.array(range(10))
print("Array:{}".format(bigarray))

Array:[0 1 2 3 4 5 6 7 8 9]


In [35]:
bigArray = np.array(range(10))
print("Array: {}".format(bigArray))

Array: [0 1 2 3 4 5 6 7 8 9]


In [36]:
# Slice array from index 0 to 4

print("Array value from index 0 to 4: {}".format(bigArray[:5]))

Array value from index 0 to 4: [0 1 2 3 4]


In [37]:
# Masking using boolean values and operators
mask = (bigArray > 6) | (bigArray < 3)
print(mask)
print("Array values with mask as true: {}".format(bigArray[mask]))

[ True  True  True False False False False  True  True  True]
Array values with mask as true: [0 1 2 7 8 9]


# List and numpy comparison

In [44]:
arr1 = np.arange(5)

In [45]:
arr1

array([0, 1, 2, 3, 4])

In [50]:
#import numpy as np
import time
# let's declare the size
Size = 10000
# Creating two lists
list1 = range(Size)
list2 = range(Size)
# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)
# Calculating time for Python list
start = time.time()
result1 = [(x + y) for x, y in zip(list1, list2)]
print("Time for Python List in msec: ", (time.time() - start) )
# Calculating time for NumPy array
start = time.time()
result2 = (arr1 + arr2)
print("Time for NumPy array in msec: ", (time.time()- start) )

Time for Python List in msec:  33.93205547332764
Time for NumPy array in msec:  7.264230728149414


# Task for you

1. Write a Python program that accepts a string and calculate the number of digits and letters

2. Write a Python program to check a string represent an integer or not?

In [65]:
s = input()

4


In [66]:
print(s)

4


In [67]:
s + 1

TypeError: can only concatenate str (not "int") to str

In [68]:
type(s)

str

In [69]:
a = int(input())

312


In [70]:
type(a)

int

In [71]:
a+1

313

In [72]:
#Write a Python program that accepts a string and calculate the number of digits and letters
s = input("Input a string ")
d=0
l=0
for c in s:
    if c.isdigit():
        d=d+1
    elif c.isalpha():
        l=l+1
    else:
        pass
print("Letters", l)
print("Digits", d)

Input a string abcde123
Letters 5
Digits 3


In [74]:
#Write a Python program to check a string represent an integer or not?
text = '12323'
flag = 0
for i in text:
    if i not in '0123456789':
        flag = 1
        break
if flag ==1 :
    print('Not an integer')
else:
    print('Integer')

Integer


In [1]:
import requests
r = requests.get('https://www.nytimes.com/interactive/2017/06/23/opinion/trumps-lies.html')

from bs4 import BeautifulSoup
soup = BeautifulSoup(r.text, 'html.parser')
results = soup.find_all('span', attrs={'class':'short-desc'})

records = []
for result in results:
    date = result.find('strong').text[0:-1] + ', 2017'
    lie = result.contents[1][1:-2]
    explanation = result.find('a').text[1:-1]
    url = result.find('a')['href']
    records.append((date, lie, explanation, url))

import pandas as pd
df = pd.DataFrame(records, columns=['date', 'lie', 'explanation', 'url'])
df['date'] = pd.to_datetime(df['date'])
df.to_csv('trump_lies.csv', index=False, encoding='utf-8')

In [2]:
df

date                                                lie  \
0   2017-01-21  I wasn't a fan of Iraq. I didn't want to go in...   
1   2017-01-21  A reporter for Time magazine — and I have been...   
2   2017-01-23  Between 3 million and 5 million illegal votes ...   
3   2017-01-25  Now, the audience was the biggest ever. But th...   
4   2017-01-25  Take a look at the Pew reports (which show vot...   
..         ...                                                ...   
175 2017-10-25      We have trade deficits with almost everybody.   
176 2017-10-27  Wacky & totally unhinged Tom Steyer, who has b...   
177 2017-11-01  Again, we're the highest-taxed nation, just ab...   
178 2017-11-07  When you look at the city with the strongest g...   
179 2017-11-11  I'd rather have him  – you know, work with him...   

                                           explanation  \
0     He was for an invasion before he was against it.   
1    Trump was on the cover 11 times and Nixon appe...   
2               There's no evidence of illegal voting.   
3    Official aerial photos show Obama's 2009 inaug...   
4              The report never mentioned voter fraud.   
..                                                 ...   
175  We have trade surpluses with more than 100 cou...   
176  Steyer has financially supported many winning ...   
177                                         We're not.   
178  Several other cities, including New York and L...   
179  There is no evidence that Democrats "set up" R...   

                                                   url  
0    https://www.buzzfeed.com/andrewkaczynski/in-20...  
1    http://nation.time.com/2013/11/06/10-things-yo...  
2    https://www.nytimes.com/2017/01/23/us/politics...  
3    https://www.nytimes.com/2017/01/21/us/politics...  
4    https://www.nytimes.com/2017/01/24/us/politics...  
..                                                 ...  
175  https://www.bea.gov/newsreleases/international...  
176  https://www.opensecrets.org/donor-lookup/resul...  
177  http://www.politifact.com/truth-o-meter/statem...  
178  http://www.politifact.com/truth-o-meter/statem...  
179  https://www.nytimes.com/interactive/2017/12/10...  

[180 rows x 4 columns]